### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by andysingal** [loevlie/GPT4Readability#2]
Hi, 
    Thanks for the amazing repo: https://github.com/andysingal/Reinforcement_Learning
i git cloned my repo to create README file
```
!git clone https://github.com/andysingal/Reinforcement_Learning
!pip install GPT4Readability==0.0.7
!gpt4readability /content/Reinforcement_Learning --function readme --output_readme README.md --model "gpt-3.5-turbo"
```
ERROR:
```
OPENAI_API_KEY environment variable not found. Please input it:
Password: 

[INFO] Commencing README generation using gpt-3.5-turbo. Initiating a detailed search and understanding of your codebase. This may take a while depending on the size of your codebase.

Traceback (most recent call last):
  File "/usr/local/bin/gpt4readability", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/GPT4Readability/__main__.py", line 31, in main
    generate_readme(path, output_readme, model)
  File "/usr/local/lib/python3.10/dist-packages/GPT4Readability/readme_gen.py", line 44, in generate_readme
    LOCAL_vector_store = makeEmbeddings(texts)
  File "/usr/local/lib/python3.10/dist-packages/GPT4Readability/utils.py", line 157, in makeEmbeddings
    vector_store = FAISS.from_documents(chunked_docs, embedder)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/base.py", line 419, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/faiss.py", line 604, in from_texts
    return cls.__from(
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/faiss.py", line 563, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
IndexError: list index out of range
```

**Comment by loevlie** [comment]
Hi @andysingal, 

Thank you for checking out GPT4Readability!  I believe the problem here is that (for now) the package only reads python (.py) files.  Getting it to understand Jupyter Notebook files as well is definitely on my list of things to add though!

Best,
Denny

**Comment by andysingal** [comment]
Thanks Danny, I will store the file in  .py format. I will keep you posted
on the results. Thanks

**Comment by DoctorGoose** [comment]
Seconding this, when it can read notebooks and knows to filter out unreadable file types I'll happily test on several repositories.

**Comment by loevlie** [comment]
My first thought is to simply convert the Jupyter Notebook files into full markdown syntax.  If that works, I will try and get that done asap and release a new version that reads Jupyter Notebook files.  I can also add error handling that provides a more readable error than the one above when the package does not find any readable file types in the directory provided.

**Comment by andysingal** [comment]
Thanks for the update Dennis. I was using pdoc3 to create documentation for
code. I think your application is more powerful and descriptive. Looking
forward to the new release.

**Comment by loevlie** [comment]
@andysingal @DoctorGoose It will be updated by the end of the week and I will let this thread know when its done.

**Comment by loevlie** [comment]
@andysingal @DoctorGoose Please try version 0.1.3 released today.  I added (experimental) support for .ipynb and optionally (sometimes you may not want them to be included/excluded) .md files to be used by GPT4Readability for context about the code repository.  

P.S. The package is still text based so I remove any images in Jupyter Notebook files before feeding them into the database. Eventually I would like to get it understanding the meaning of images within the repository it's run on!  Maybe even adding images in the README from a folder the user provides.  These are still just ideas for the future of the package though.

**Comment by DoctorGoose** [comment]
@loevlie Success with version 0.1.3. I've only tested one repo so far (https://github.com/DoctorGoose/Paracrine-IFN), but it did an excellent job.

**Comment by andysingal** [comment]
> @loevlie Success with version 0.1.3. I've only tested one repo so far (https://github.com/DoctorGoose/Paracrine-IFN), but it did an excellent job.

Greetings @loevlie , i am still getting an error: https://colab.research.google.com/drive/14SS2YDaCpMwN4VD_7Q35dtUOBwTVT-n9?usp=sharing

**Comment by DoctorGoose** [comment]
@andysingal try running gpt4readability from within the directory you want to summarize? That's the only difference in out workflows I can see.

One thing to note, I get a partial failure after Readme gen, looking for an include.md in the get_docs function.

Minor feedback, but the generated Support section usually has a link to an imaginary email:
![image](https://github.com/loevlie/GPT4Readability/assets/113361625/f4b526a4-a039-45bb-a0d0-28ca2168ee22)

**Comment by loevlie** [comment]
@andysingal Yes as @DoctorGoose said it will need to be in the root of the directory but also it at the moment needs to be a Github repository (meaning it's stored on Github somewhere publicly) because I parse some of your username info for the badges at the top of the README.  Next I will try and release a version that checks if it's a Github repo and if not just deletes the badges.  I will keep you updated.  

@DoctorGoose Hmm I am not sure why the partial failure happens yet but I will investigate that.  As of the imaginary email I haven't seen that yet thank you!  I have also seen that sometimes fake license details when their is not one.  I was trying to fix that by adding to the prompt information but it seems it still hallucinates.  I may try to check the readme for these mistakes after it gets generated and fix them programmatically in a future version of the package!!  I will keep you updated if I make those changes.
