### ISSUE TITLE
Had a question about the capability of the codebase

### ISSUE THREAD

**Issue by anshumankmr** [loevlie/GPT4Readability#3]
> Repository Support: Capable of handling repositories of up to 8300 text segments

What does this mean? 8300 text files? Just wanted to clarify.

**Comment by anshumankmr** [comment]
In the utils file, I saw that currently, this is being used. Could this be the cause of potentially not being able to handle larger text segment? 
![image](https://github.com/loevlie/GPT4Readability/assets/24219264/d1eb3165-8ac5-47a4-ae7b-947cdcd0898f)
Optionally, we could use map_reduce I think.

LMK if PRs are acceptable.

**Comment by anshumankmr** [comment]
> > Repository Support: Capable of handling repositories of up to 8300 text segments
> 
> What does this mean? 8300 text files? Just wanted to clarify.

As for this, it seems I have determined what you meant here.

>def split_docs(docs):
    text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
    texts = text_splitter.split_documents(docs)
    return texts
 

So since you are using CharacterTextSplitter, if that has more than 8300 chunks, this will not work.
For the PR thing, I have a few ideas for enhancements, I will try and push those in my free time, ie like supporting models, and a few more. Will keep ya posted. For now, I am however closing the issue.

**Comment by loevlie** [comment]
@anshumankmr Sorry for the late reply!  It's actually more of a problem with how many chunks the openai API could handle last summer.  This most likely has changed but if I sent more than roughly 8,300 through it would cause issues so I manually set that capacity of 8,300 in the code.

**Comment by anshumankmr** [comment]
Right. That does make sense. Open AI does support upto 4x more data, and possibly more whenever GPT 5 does actually come out.
